# Release packagers supply one tested, platform-specific runtime payload.
# End users do not install a database, shell, Git, Docker, or build tools.
set(CREATOR_RUNTIME_BUNDLE "" CACHE PATH "Prepared Runtime directory to include in Creator installation")
if(CREATOR_RUNTIME_BUNDLE)
  if(CMAKE_VERSION VERSION_LESS 3.21)
    message(FATAL_ERROR "Portable Creator packaging requires CMake 3.21 or newer")
  endif()
  if(NOT USE_SQL OR NOT MYSQL_LIBRARY OR NOT MYSQL_INCLUDE_DIR)
    message(FATAL_ERROR "Creator authoring requires the MariaDB/MySQL client development library when building Noggit.")
  endif()
  foreach(required creator-runtime.json MariaDB/bin/mariadbd${CMAKE_EXECUTABLE_SUFFIX}
      MariaDB/bin/mariadb${CMAKE_EXECUTABLE_SUFFIX} realmd/realmd${CMAKE_EXECUTABLE_SUFFIX}
      mangosd/mangosd${CMAKE_EXECUTABLE_SUFFIX} realmd/realmd.conf.dist
      mangosd/mangosd.conf.dist mangosd/modules/mod-creator-test.conf.dist DatabaseSeed/mysql)
    if(NOT EXISTS "${CREATOR_RUNTIME_BUNDLE}/${required}")
      message(FATAL_ERROR "Incomplete Creator runtime: ${required}")
    endif()
  endforeach()
  # Check at configure AND install time so a stale configured build cannot ship without data.
  configure_file("${CMAKE_SOURCE_DIR}/cmake/ValidateCreatorRuntime.cmake.in"
      "${CMAKE_BINARY_DIR}/ValidateCreatorRuntime.cmake" @ONLY)
  include("${CMAKE_BINARY_DIR}/ValidateCreatorRuntime.cmake")
  install(SCRIPT "${CMAKE_BINARY_DIR}/ValidateCreatorRuntime.cmake" COMPONENT Creator)
  install(DIRECTORY "${CREATOR_RUNTIME_BUNDLE}/" DESTINATION Runtime USE_SOURCE_PERMISSIONS COMPONENT Creator)
  install(TARGETS noggit RUNTIME DESTINATION Noggit COMPONENT Creator
      BUNDLE DESTINATION Noggit COMPONENT Creator)
  install(DIRECTORY "${CMAKE_SOURCE_DIR}/dist/themes" "${CMAKE_SOURCE_DIR}/dist/definitions"
      DESTINATION Noggit COMPONENT Creator PATTERN ".git" EXCLUDE)
  install(DIRECTORY "${CMAKE_SOURCE_DIR}/dist/listfile/" DESTINATION Noggit COMPONENT Creator PATTERN ".git" EXCLUDE)
  # Stage the deployed Qt plugins and DLLs alongside the installed executable.
  # On Linux the preparation tool stages the non-system shared libraries.
  install(DIRECTORY "$<TARGET_FILE_DIR:noggit>/" DESTINATION Noggit COMPONENT Creator
      FILES_MATCHING PATTERN "*.dll" PATTERN "*.so*" PATTERN "*.spv" PATTERN "qt.conf")
  if(WIN32)
    # The legacy MySQL client is rebound by prepare_runtime to the bundled VC90 CRT.
    # Replace the build's original DLL so every process uses the same private assembly.
    foreach(legacy_file libmySQL.dll msvcr90.dll msvcp90.dll msvcm90.dll Microsoft.VC90.CRT.manifest)
      if(EXISTS "${CREATOR_RUNTIME_BUNDLE}/mangosd/${legacy_file}")
        install(FILES "${CREATOR_RUNTIME_BUNDLE}/mangosd/${legacy_file}" DESTINATION Noggit COMPONENT Creator)
      else()
        message(FATAL_ERROR "Prepared Windows runtime is missing ${legacy_file}; rerun prepare_runtime.py")
      endif()
    endforeach()
    get_filename_component(compiler_bin "${CMAKE_CXX_COMPILER}" DIRECTORY)
    find_program(CREATOR_DUMPBIN dumpbin HINTS "${compiler_bin}" REQUIRED)
    get_filename_component(vc_root "${compiler_bin}/../../../../../.." ABSOLUTE)
    file(GLOB crt_directories "${vc_root}/Redist/MSVC/*/x64/Microsoft.VC*.CRT")
    if(NOT crt_directories)
      message(FATAL_ERROR "MSVC x64 redistributable DLLs were not found under ${vc_root}/Redist; install the compiler redistributable files on the build machine")
    endif()
    list(SORT crt_directories COMPARE NATURAL ORDER DESCENDING)
    list(GET crt_directories 0 crt_directory)
    file(GLOB crt_dlls "${crt_directory}/*.dll")
    foreach(destination Noggit Runtime/realmd Runtime/mangosd Runtime/MariaDB/bin Runtime/OpenSSH)
      install(FILES ${crt_dlls} DESTINATION "${destination}" COMPONENT Creator)
    endforeach()
    install(CODE "execute_process(COMMAND \"${_qt_bin_dir}/windeployqt.exe\" --release --compiler-runtime \"\${CMAKE_INSTALL_PREFIX}/Noggit/noggit.exe\" RESULT_VARIABLE result)
      if(NOT result EQUAL 0)
        message(FATAL_ERROR \"Qt deployment failed\")
      endif()" COMPONENT Creator)
  else()
    get_target_property(qmake Qt5::qmake IMPORTED_LOCATION)
    execute_process(COMMAND "${qmake}" -query QT_INSTALL_PLUGINS OUTPUT_VARIABLE qt_plugins OUTPUT_STRIP_TRAILING_WHITESPACE)
    execute_process(COMMAND "${qmake}" -query QT_INSTALL_LIBS OUTPUT_VARIABLE CREATOR_QT_LIBS OUTPUT_STRIP_TRAILING_WHITESPACE)
    install(DIRECTORY "${qt_plugins}/platforms" "${qt_plugins}/imageformats"
        DESTINATION Noggit/plugins COMPONENT Creator)
    foreach(plugin_directory audio mediaservice bearer)
      if(EXISTS "${qt_plugins}/${plugin_directory}")
        install(DIRECTORY "${qt_plugins}/${plugin_directory}" DESTINATION Noggit/plugins COMPONENT Creator)
      endif()
    endforeach()
    file(WRITE "${CMAKE_BINARY_DIR}/creator-qt.conf" "[Paths]\nPlugins=plugins\n")
    install(FILES "${CMAKE_BINARY_DIR}/creator-qt.conf" DESTINATION Noggit RENAME qt.conf COMPONENT Creator)
    set_target_properties(noggit PROPERTIES INSTALL_RPATH "$ORIGIN/../Runtime/lib")
    # The launcher also supplies the path for plugins and bundled MariaDB libraries.
    file(WRITE "${CMAKE_BINARY_DIR}/start-creator" "#!/bin/sh\ncreator_root=\"$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\"\nexport LD_LIBRARY_PATH=\"$creator_root/Runtime/lib:$creator_root/Runtime/MariaDB/lib\${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"\nexec \"$creator_root/Noggit/noggit\" \"$@\"\n")
    install(PROGRAMS "${CMAKE_BINARY_DIR}/start-creator" DESTINATION . COMPONENT Creator)
  endif()
  configure_file("${CMAKE_SOURCE_DIR}/cmake/InstallCreatorDependencies.cmake.in"
      "${CMAKE_BINARY_DIR}/InstallCreatorDependencies.cmake" @ONLY)
  install(SCRIPT "${CMAKE_BINARY_DIR}/InstallCreatorDependencies.cmake" COMPONENT Creator)
  install(FILES "${CMAKE_SOURCE_DIR}/COPYING" DESTINATION Noggit COMPONENT Creator)
  set(CPACK_GENERATOR ZIP)
  set(CPACK_PACKAGE_FILE_NAME "Noggit-Creator-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
  set(CPACK_PACKAGE_NAME "Noggit-Creator")
  set(CPACK_PACKAGE_VERSION "3")
  set(CPACK_COMPONENTS_ALL Creator)
  set(CPACK_INSTALL_CMAKE_PROJECTS "${CMAKE_BINARY_DIR};${CMAKE_PROJECT_NAME};Creator;/")
  set(CPACK_ARCHIVE_COMPONENT_INSTALL OFF)
  include(CPack)
endif()
