#include <noggit/errorHandling.h>
#include <noggit/Log.h>

#include <atomic>
#include <csignal>
#include <cstdint>
#include <cstdlib>
#include <exception>
#include <iostream>
#include <string>
#include <vector>

#ifndef WIN32
  #include <execinfo.h>
#else
  #include <win/StackWalker.h>
  #include <errhandlingapi.h>

namespace
{
  // StackWalker writes to OutputDebugString/printf by default, which vanish in a GUI build (no
  // console). Route every line to std::cerr instead -- InitLogging redirects std::cerr to log.txt,
  // so the crash callstack lands in the log. Flush each line so nothing is lost when we crash.
  class LogStackWalker : public StackWalker
  {
  protected:
    void OnOutput(LPCSTR szText) override
    {
      std::cerr << szText;
      std::cerr.flush();
    }
  };
}
#endif

namespace Noggit
{
  void printStacktrace()
  {
#ifndef WIN32
    std::vector<void*> frames  (32);

    std::size_t actual  (0);
    while ((actual = backtrace (frames.data(), frames.size())) == frames.size())
    {
      frames.resize (frames.size() * 2);
    }
    frames.resize (actual);
    char** strings (backtrace_symbols (frames.data(), frames.size()));

    LogError << "Obtained " << frames.size() << " stack frames." << std::endl;

    for (size_t i (0); i < frames.size(); ++i)
      LogError << "- " << strings[i] << std::endl;

    free (strings);
#else
    // RE-ENTRANCY GUARD. StackWalker formats frames with _snprintf_s; an unresolvable frame can trip
    // the CRT invalid-parameter handler, which calls back into here -- an infinite two-frame loop that
    // overwrites the real crash report. Walk once; report (don't recurse on) a fault during the walk.
    static std::atomic<bool> s_walking{false};
    bool expected = false;
    if (!s_walking.compare_exchange_strong(expected, true))
    {
      LogError << "  <fault raised while walking the stack -- suppressed to preserve the report above>"
               << std::endl;
      return;
    }
    struct ClearOnExit
    {
      std::atomic<bool>& flag;
      ~ClearOnExit() { flag.store(false); }
    } clear_on_exit{s_walking};

    LogStackWalker sw;
    sw.ShowCallstack();
#endif
  }

  namespace
  {
    void leave (int sig)
    {
      // Reset to defaults.
      signal (SIGABRT, SIG_DFL);
      signal (SIGFPE, SIG_DFL);
      signal (SIGILL, SIG_DFL);
      signal (SIGSEGV, SIG_DFL);
      signal (SIGTERM, SIG_DFL);

      std::string description;
      std::string sign;

      switch (sig)
      {
      case SIGABRT:
        sign = "SIGABRT";
        description = "Abnormal termination, such as instigated by the abort function. (Abort.)";
        break;
      case SIGFPE:
        sign = "SIGFPE";
        description = "Erroneous arithmetic operation, such as divide by 0 or overflow. (Floating point exception.)";
      break;
      case SIGILL:
        sign = "SIGILL";
        description = "An ‘invalid object program’ has been detected. This usually means that there is an illegal instruction in the program. (Illegal instruction.)";
        break;
      case SIGINT:
        sign = "SIGINT";
        description = "Interactive attention signal; on interactive systems this is usually generated by typing some ‘break-in’ key at the terminal. (Interrupt.)";
        break;
      case SIGSEGV:
        sign = "SIGSEGV";
        description = "Invalid storage access; most frequently caused by attempting to store some value in an object pointed to by a bad pointer. (Segment violation.)";
        break;
      case SIGTERM:
        sign = "SIGTERM";
        description = "Termination request made to the program. (Terminate.)";
        break;
      default:
        sign = "SIGUNK";
        description = "Unknown Exception!";
        break;
      }

      LogError << "There was an exception of type \""
        << sign
        << "\"\n\""
        << description
        << "\".\nPlease excuse the inconvenience. You may want to report this error including the log to the developers.\n"
        << std::endl;

      printStacktrace();

      exit (sig);
    }

#ifdef _WIN32
    LONG WINAPI windows_exception_handler(EXCEPTION_POINTERS * ExceptionInfo)
    {
      auto code = ExceptionInfo->ExceptionRecord->ExceptionCode;

      switch (code)
      {
      case EXCEPTION_ACCESS_VIOLATION: LogError << "EXCEPTION_ACCESS_VIOLATION" << std::endl; break;
      case EXCEPTION_DATATYPE_MISALIGNMENT: LogError << "EXCEPTION_DATATYPE_MISALIGNMENT" << std::endl; break;
      case EXCEPTION_BREAKPOINT: LogError << "EXCEPTION_BREAKPOINT" << std::endl; break;
      case EXCEPTION_SINGLE_STEP: LogError << "EXCEPTION_SINGLE_STEP" << std::endl; break;
      case EXCEPTION_ARRAY_BOUNDS_EXCEEDED: LogError << "EXCEPTION_ARRAY_BOUNDS_EXCEEDED" << std::endl; break;
      case EXCEPTION_FLT_DENORMAL_OPERAND: LogError << "EXCEPTION_FLT_DENORMAL_OPERAND" << std::endl; break;
      case EXCEPTION_FLT_DIVIDE_BY_ZERO: LogError << "EXCEPTION_FLT_DIVIDE_BY_ZERO" << std::endl; break;
      case EXCEPTION_FLT_INEXACT_RESULT: LogError << "EXCEPTION_FLT_INEXACT_RESULT" << std::endl; break;
      case EXCEPTION_FLT_INVALID_OPERATION: LogError << "EXCEPTION_FLT_INVALID_OPERATION" << std::endl; break;
      case EXCEPTION_FLT_OVERFLOW: LogError << "EXCEPTION_FLT_OVERFLOW" << std::endl; break;
      case EXCEPTION_FLT_STACK_CHECK: LogError << "EXCEPTION_FLT_STACK_CHECK" << std::endl; break;
      case EXCEPTION_FLT_UNDERFLOW: LogError << "EXCEPTION_FLT_UNDERFLOW" << std::endl; break;
      case EXCEPTION_INT_DIVIDE_BY_ZERO: LogError << "EXCEPTION_INT_DIVIDE_BY_ZERO" << std::endl; break;
      case EXCEPTION_INT_OVERFLOW: LogError << "EXCEPTION_INT_OVERFLOW" << std::endl; break;
      case EXCEPTION_PRIV_INSTRUCTION: LogError << "EXCEPTION_PRIV_INSTRUCTION" << std::endl; break;
      case EXCEPTION_IN_PAGE_ERROR: LogError << "EXCEPTION_IN_PAGE_ERROR" << std::endl; break;
      case EXCEPTION_ILLEGAL_INSTRUCTION: LogError << "EXCEPTION_ILLEGAL_INSTRUCTION" << std::endl; break;
      case EXCEPTION_NONCONTINUABLE_EXCEPTION: LogError << "EXCEPTION_NONCONTINUABLE_EXCEPTION" << std::endl; break;
      case EXCEPTION_STACK_OVERFLOW: LogError << "EXCEPTION_STACK_OVERFLOW" << std::endl; break;
      case EXCEPTION_INVALID_DISPOSITION: LogError << "EXCEPTION_INVALID_DISPOSITION" << std::endl; break;
      case EXCEPTION_GUARD_PAGE: LogError << "EXCEPTION_GUARD_PAGE" << std::endl; break;
      case EXCEPTION_INVALID_HANDLE: LogError << "EXCEPTION_INVALID_HANDLE" << std::endl; break;
#ifdef STATUS_POSSIBLE_DEADLOCK
      case EXCEPTION_POSSIBLE_DEADLOCK: LogError << "EXCEPTION_POSSIBLE_DEADLOCK" << std::endl; break;
#endif
      default:
        LogError << "Exception code=" << code << std::endl;
      }

      printStacktrace();

      return EXCEPTION_CONTINUE_SEARCH;
    }

    // Vectored exception handler: runs on the FAULTING thread the instant a hardware exception is
    // raised -- before SEH unwinding, before any __fastfail, and it can't be replaced the way
    // SetUnhandledExceptionFilter can (Qt etc.). Crucially we walk from ep->ContextRecord, so the
    // logged callstack is the actual CRASH site (not this handler's frame). Output goes to log.txt
    // via LogStackWalker. Only fatal hardware codes, capped, so handled first-chance faults don't
    // spam -- the unhandled crash is the last one logged before the process dies.
    LONG WINAPI vectored_exception_handler(EXCEPTION_POINTERS* ep)
    {
      DWORD const code = ep->ExceptionRecord->ExceptionCode;
      bool const fatal =
           code == EXCEPTION_ACCESS_VIOLATION
        || code == EXCEPTION_ILLEGAL_INSTRUCTION
        || code == EXCEPTION_STACK_OVERFLOW
        || code == EXCEPTION_INT_DIVIDE_BY_ZERO
        || code == EXCEPTION_PRIV_INSTRUCTION
        || code == EXCEPTION_IN_PAGE_ERROR
        || code == EXCEPTION_ARRAY_BOUNDS_EXCEEDED
        || code == EXCEPTION_DATATYPE_MISALIGNMENT;

      if (fatal)
      {
        static std::atomic<int> logged{0};
        if (logged.fetch_add(1) < 8)
        {
          std::cerr << "\n=== [VEH] fatal exception 0x" << std::hex << code
                    << " at " << ep->ExceptionRecord->ExceptionAddress << std::dec
                    << " (thread " << GetCurrentThreadId() << ") ===\n";
          std::cerr.flush();
          LogStackWalker sw;
          sw.ShowCallstack(GetCurrentThread(), ep->ContextRecord);
          std::cerr << "=== [VEH] end callstack ===\n";
          std::cerr.flush();
        }
      }

      return EXCEPTION_CONTINUE_SEARCH;
    }
#endif

  }

  namespace
  {
    // std::terminate is reached by an unhandled C++ exception, an exception escaping a noexcept function
    // or a destructor during unwind, or a rethrow with no active exception. On MSVC it goes straight to
    // __fastfail, which bypasses the vectored/SEH handlers above -- so those crashes leave NO callstack
    // in the log (the classic "died with a clean log" symptom). Log the active exception + a stack here.
    [[noreturn]] void on_terminate()
    {
      LogError << "\n=== std::terminate() -- unhandled C++ exception / noexcept violation (thread "
#ifdef _WIN32
               << GetCurrentThreadId()
#endif
               << ") ===" << std::endl;
      if (auto const ex = std::current_exception())
      {
        try { std::rethrow_exception(ex); }
        catch (std::exception const& e) { LogError << "  active exception: " << e.what() << std::endl; }
        catch (...) { LogError << "  active exception: <non-std type>" << std::endl; }
      }
      else
      {
        LogError << "  (no active exception -- likely a bad rethrow or a direct std::terminate call)" << std::endl;
      }
      printStacktrace();
      std::cerr << "=== end terminate ===" << std::endl;
      std::cerr.flush();
      std::abort();
    }

#ifdef _WIN32
    // The CRT invalid-parameter handler (bad iterator, sprintf with a null, etc.) and a pure-virtual
    // call BOTH __fastfail silently by default. Route them through the stack logger too.
    void on_invalid_parameter(wchar_t const*, wchar_t const*, wchar_t const*, unsigned int, uintptr_t)
    {
      // A second fatal event (including one raised by the stack walk itself) must not restart the
      // report -- abort straight away so the FIRST report survives intact.
      static std::atomic<bool> s_in_handler{false};
      bool expected = false;
      if (!s_in_handler.compare_exchange_strong(expected, true))
      {
        std::abort();
      }
      LogError << "\n=== CRT invalid parameter (thread " << GetCurrentThreadId() << ") ===" << std::endl;
      printStacktrace();
      std::cerr.flush();
      std::abort();
    }

    void on_purecall()
    {
      LogError << "\n=== pure virtual function call (thread " << GetCurrentThreadId() << ") ===" << std::endl;
      printStacktrace();
      std::cerr.flush();
      std::abort();
    }
#endif
  }

  void RegisterErrorHandlers()
  {
#ifdef _WIN32
    AddVectoredExceptionHandler(1 /*call first*/, vectored_exception_handler);
    SetUnhandledExceptionFilter(windows_exception_handler);
    _set_invalid_parameter_handler(on_invalid_parameter);
    _set_purecall_handler(on_purecall);
#endif

    std::set_terminate(on_terminate);

    signal (SIGABRT, leave);
    signal (SIGFPE, leave);
    signal (SIGILL, leave);
    signal (SIGSEGV, leave);
    signal (SIGTERM, leave);
  }
}
